### ISSUE TITLE
multiple broadcast rooms

### ISSUE THREAD

**Issue by arnoschutijzer** [arnoschutijzer/rad.io#18]
there should be a form to create a 'broadcast room'.
user would enter an ID & description/topic. these have to be persisted and displayed in a 'browse' view where a user can join the room.

## TODO
- [x] create view/popup to make a room
- [x] persist rooms & update 'browse' view
- [x] different chat per room (socket.io supports this IIRC)
- [x] link user to rooms (`onConnect` & `onDisconnect` in both front- & backend)
- [x] update state to represent message rooms. currently the state is a single `messages` array, and should be changed into an object with keys and arrays e.g.
```
{
  "123_ID": [ ]
}
```

**Comment by arnoschutijzer** [comment]
related: https://socket.io/docs/rooms-and-namespaces/

**Comment by arnoschutijzer** [comment]
related: https://github.com/auth0/socketio-jwt
